# Generated by Django 4.0.1 on 2022-02-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_tag_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(blank=True, help_text='Ctrl + click to select multiple', max_length=30),
        ),
    ]
