# Generated by Django 4.0.1 on 2022-02-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='rate',
        ),
        migrations.AddField(
            model_name='rate',
            name='value',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
        ),
    ]
